# Gap-fill NEON total CH4 flux and estimate annual site budgets.
#
# Uses the total flux generated by flow.TotalFlux.R:
#   flux_total = FG_ENSEMBLE_RSHP + storage_flux_filled
#
# Uncertainty reported here is gap-fill/model uncertainty. The total-flux
# product does not include explicit measurement or storage-flux uncertainty, so
# those terms are not propagated.

library(tidyverse)
library(mgcv)
library(ggplot2)

localdir.ch4 <- '/Volumes/MaloneLab/Research/FluxGradient/Methane'
load( fs::path(localdir.ch4 ,paste0("SITE_DATA_FILTERED_Final_RSHP_ENSEMBLE_TotalFlux.Rdata")) )
setwd( localdir.ch4 )

dir.create("OUTPUT", showWarnings = FALSE)
dir.create("FIGURES", showWarnings = FALSE)

localdir_ch4_candidates <- c(
  "/Volumes/MaloneLab/Research/FluxGradient/Methane",
  "/Volumes/MaloneLab/Research/FluxGradient/METHANE"
)

total_flux_file <- file.path(
  localdir_ch4_candidates,
  "SITE_DATA_FILTERED_Final_RSHP_ENSEMBLE_TotalFlux.Rdata"
) %>%
  .[file.exists(.)] %>%
  first()

if (is.na(total_flux_file)) {
  stop(
    "Could not find SITE_DATA_FILTERED_Final_RSHP_ENSEMBLE_TotalFlux.Rdata in: ",
    paste(localdir_ch4_candidates, collapse = ", "),
    ". Run flow.TotalFlux.R first."
  )
}

load(total_flux_file)

if (!exists("SITE_DATA_FILTERED_Final_RSHP_ENSEMBLE_storage")) {
  stop("Expected object SITE_DATA_FILTERED_Final_RSHP_ENSEMBLE_storage was not found in total-flux RData.")
}

required_cols <- c(
  "time.rounded", "FG_ENSEMBLE_RSHP", "storage_flux_filled", "flux_total",
  "count", "PAR", "Tair_C"
)

missing_by_site <- purrr::imap_dfr(
  SITE_DATA_FILTERED_Final_RSHP_ENSEMBLE_storage,
  function(site_df, site) {
    tibble(SITE_ID = site, missing_cols = paste(setdiff(required_cols, names(site_df)), collapse = ", "))
  }
) %>%
  filter(missing_cols != "")

if (nrow(missing_by_site) > 0) {
  stop(
    "Some site data frames are missing required total-flux columns. First missing site: ",
    missing_by_site$SITE_ID[1],
    " (", missing_by_site$missing_cols[1], ")."
  )
}

flux_to_mgC_30min <- 2 * 0.0000288872 * 1000
min_training_obs_per_site <- 50
min_interpretable_coverage <- 0.05

total_flux <- purrr::imap_dfr(
  SITE_DATA_FILTERED_Final_RSHP_ENSEMBLE_storage,
  function(site_df, site) {
    site_df %>%
      dplyr::select(dplyr::all_of(required_cols)) %>%
      mutate(SITE_ID = site)
  }
) %>%
  mutate(
    time.rounded = as.POSIXct(time.rounded, tz = "UTC"),
    SITE_ID = as.character(SITE_ID),
    Date = as.Date(time.rounded),
    Year = as.integer(format(time.rounded, "%Y")),
    month = as.integer(format(time.rounded, "%m")),
    doy = as.integer(format(time.rounded, "%j")),
    hour_num = as.numeric(format(time.rounded, "%H")) + as.numeric(format(time.rounded, "%M")) / 60,
    season = factor(
      case_when(
        month %in% c(12, 1, 2) ~ "Winter",
        month %in% c(3, 4, 5) ~ "Spring",
        month %in% c(6, 7, 8) ~ "Summer",
        TRUE ~ "Autumn"
      ),
      levels = c("Winter", "Spring", "Summer", "Autumn")
    ),
    PAR = if_else(is.finite(PAR) & PAR > 0, PAR, 0),
    log_PAR = log1p(PAR),
    observed_flux = is.finite(flux_total)
  ) %>%
  filter(!is.na(SITE_ID), !is.na(time.rounded), !is.na(Year))

site_years <- total_flux %>%
  filter(!is.na(Year)) %>%
  distinct(SITE_ID, Year)

site_year_grid <- site_years %>%
  mutate(
    start_time = as.POSIXct(paste0(Year, "-01-01 00:00:00"), tz = "UTC"),
    end_time = as.POSIXct(paste0(Year, "-12-31 23:30:00"), tz = "UTC")
  ) %>%
  mutate(time.rounded = purrr::map2(start_time, end_time, ~ seq(.x, .y, by = "30 min"))) %>%
  dplyr::select(SITE_ID, Year, time.rounded) %>%
  tidyr::unnest(time.rounded) %>%
  mutate(
    Date = as.Date(time.rounded),
    month = as.integer(format(time.rounded, "%m")),
    doy = as.integer(format(time.rounded, "%j")),
    hour_num = as.numeric(format(time.rounded, "%H")) + as.numeric(format(time.rounded, "%M")) / 60,
    season = factor(
      case_when(
        month %in% c(12, 1, 2) ~ "Winter",
        month %in% c(3, 4, 5) ~ "Spring",
        month %in% c(6, 7, 8) ~ "Summer",
        TRUE ~ "Autumn"
      ),
      levels = c("Winter", "Spring", "Summer", "Autumn")
    )
  )

gapfill_data <- site_year_grid %>%
  left_join(
    total_flux %>%
      dplyr::select(
        SITE_ID, time.rounded, FG_ENSEMBLE_RSHP, storage_flux_filled, flux_total,
        count, PAR, Tair_C, log_PAR, observed_flux
      ),
    by = c("SITE_ID", "time.rounded")
  ) %>%
  mutate(
    observed_flux = replace_na(observed_flux, FALSE),
    count = replace_na(count, 0)
  )

site_month_hour_covariates <- total_flux %>%
  reframe(
    .by = c(SITE_ID, month, hour_num),
    Tair_site_month_hour = median(Tair_C[is.finite(Tair_C)], na.rm = TRUE),
    log_PAR_site_month_hour = median(log_PAR[is.finite(log_PAR)], na.rm = TRUE)
  )

site_month_covariates <- total_flux %>%
  reframe(
    .by = c(SITE_ID, month),
    Tair_site_month = median(Tair_C[is.finite(Tair_C)], na.rm = TRUE),
    log_PAR_site_month = median(log_PAR[is.finite(log_PAR)], na.rm = TRUE)
  )

global_month_hour_covariates <- total_flux %>%
  reframe(
    .by = c(month, hour_num),
    Tair_global_month_hour = median(Tair_C[is.finite(Tair_C)], na.rm = TRUE),
    log_PAR_global_month_hour = median(log_PAR[is.finite(log_PAR)], na.rm = TRUE)
  )

global_covariates <- total_flux %>%
  summarise(
    Tair_global = median(Tair_C[is.finite(Tair_C)], na.rm = TRUE),
    log_PAR_global = median(log_PAR[is.finite(log_PAR)], na.rm = TRUE)
  )

gapfill_data <- gapfill_data %>%
  left_join(site_month_hour_covariates, by = c("SITE_ID", "month", "hour_num")) %>%
  left_join(site_month_covariates, by = c("SITE_ID", "month")) %>%
  left_join(global_month_hour_covariates, by = c("month", "hour_num")) %>%
  mutate(
    Tair_filled = coalesce(Tair_C, Tair_site_month_hour, Tair_site_month, Tair_global_month_hour, global_covariates$Tair_global),
    log_PAR_filled = coalesce(log_PAR, log_PAR_site_month_hour, log_PAR_site_month, log_PAR_global_month_hour, global_covariates$log_PAR_global),
    SITE_ID = factor(SITE_ID),
    season = factor(season, levels = c("Winter", "Spring", "Summer", "Autumn"))
  )

training_data <- gapfill_data %>%
  filter(
    observed_flux,
    is.finite(flux_total),
    is.finite(Tair_filled),
    is.finite(log_PAR_filled),
    is.finite(hour_num),
    is.finite(doy)
  ) %>%
  mutate(SITE_ID = factor(SITE_ID)) %>%
  droplevels()

if (nrow(training_data) < 500) {
  stop("Too few finite total-flux observations to fit a gap-fill model: ", nrow(training_data), " rows.")
}

site_training_counts <- training_data %>%
  count(SITE_ID, name = "n_training_obs")

gapfill_model <- mgcv::bam(
  flux_total ~
    s(hour_num, bs = "cc", k = 12) +
    s(doy, bs = "cc", k = 20) +
    s(Tair_filled, k = 10) +
    s(log_PAR_filled, k = 10) +
    ti(Tair_filled, log_PAR_filled, k = c(5, 5)) +
    season +
    s(SITE_ID, bs = "re"),
  data = training_data,
  family = gaussian(),
  method = "fREML",
  discrete = FALSE,
  knots = list(hour_num = c(0, 24), doy = c(0.5, 366.5))
)

capture.output(
  {
    cat("NEON total-flux annual budget gap-fill model\n")
    cat("Input file:", total_flux_file, "\n")
    cat("Training observations:", nrow(training_data), "\n\n")
    print(summary(gapfill_model))
  },
  file = "OUTPUT/NEON_total_flux_gapfill_model_summary.txt"
)

model_site_levels <- levels(training_data$SITE_ID)

prediction_data <- gapfill_data %>%
  mutate(SITE_ID_original = as.character(SITE_ID)) %>%
  left_join(site_training_counts %>% mutate(SITE_ID = as.character(SITE_ID)), by = "SITE_ID") %>%
  mutate(
    n_training_obs = replace_na(n_training_obs, 0L),
    use_site_effect = SITE_ID_original %in% model_site_levels &
      n_training_obs >= min_training_obs_per_site,
    SITE_ID = factor(
      if_else(SITE_ID_original %in% model_site_levels, SITE_ID_original, model_site_levels[1]),
      levels = model_site_levels
    )
  )

prediction_population <- predict(
  gapfill_model,
  newdata = prediction_data,
  type = "response",
  se.fit = TRUE,
  exclude = "s(SITE_ID)"
)

prediction_site_fit <- rep(NA_real_, nrow(prediction_data))
prediction_site_se <- rep(NA_real_, nrow(prediction_data))
site_effect_rows <- which(prediction_data$use_site_effect)

if (length(site_effect_rows) > 0) {
  prediction_site <- predict(
    gapfill_model,
    newdata = prediction_data[site_effect_rows, , drop = FALSE],
    type = "response",
    se.fit = TRUE
  )

  prediction_site_fit[site_effect_rows] <- as.numeric(prediction_site$fit)
  prediction_site_se[site_effect_rows] <- as.numeric(prediction_site$se.fit)
}

prediction_fit <- if_else(
  prediction_data$use_site_effect,
  prediction_site_fit,
  as.numeric(prediction_population$fit)
)

prediction_se <- if_else(
  prediction_data$use_site_effect,
  prediction_site_se,
  as.numeric(prediction_population$se.fit)
)

gapfilled_30min <- gapfill_data %>%
  mutate(
    pred_flux_total = prediction_fit,
    pred_flux_total_se = prediction_se,
    prediction_uses_site_effect = prediction_data$use_site_effect,
    gapfilled_flux_total = if_else(observed_flux, flux_total, pred_flux_total),
    gapfilled = !observed_flux,
    gapfilled_CH4_mgC_30min = gapfilled_flux_total * flux_to_mgC_30min,
    FG_ENSEMBLE_RSHP_mgC_30min = FG_ENSEMBLE_RSHP * flux_to_mgC_30min,
    storage_flux_filled_mgC_30min = storage_flux_filled * flux_to_mgC_30min,
    observed_CH4_mgC_30min = flux_total * flux_to_mgC_30min,
    pred_CH4_mgC_30min = pred_flux_total * flux_to_mgC_30min
  ) %>%
  left_join(site_training_counts %>% mutate(SITE_ID = as.character(SITE_ID)), by = "SITE_ID") %>%
  mutate(n_training_obs = replace_na(n_training_obs, 0L))

training_residuals <- training_data %>%
  mutate(
    fitted_flux_total = fitted(gapfill_model),
    residual_flux_total = flux_total - fitted_flux_total,
    residual_mgC_30min = residual_flux_total * flux_to_mgC_30min,
    Date = as.Date(time.rounded)
  )

daily_residual_sd_site <- training_residuals %>%
  reframe(
    .by = c(SITE_ID, Date),
    n_obs_day = dplyr::n(),
    daily_residual_gC_m2_day = sum(residual_mgC_30min, na.rm = TRUE) * 48 / n_obs_day / 1000
  ) %>%
  filter(n_obs_day >= 6, is.finite(daily_residual_gC_m2_day)) %>%
  reframe(
    .by = SITE_ID,
    n_residual_days = dplyr::n(),
    daily_residual_sd_gC = sd(daily_residual_gC_m2_day, na.rm = TRUE)
  ) %>%
  mutate(SITE_ID = as.character(SITE_ID))

global_daily_residual_sd <- daily_residual_sd_site %>%
  filter(is.finite(daily_residual_sd_gC), n_residual_days >= 5) %>%
  summarise(value = median(daily_residual_sd_gC, na.rm = TRUE)) %>%
  pull(value)

if (!is.finite(global_daily_residual_sd)) {
  global_daily_residual_sd <- sigma(gapfill_model) * flux_to_mgC_30min * sqrt(48) / 1000
}

annual_budget <- gapfilled_30min %>%
  mutate(
    prediction_variance_gC2 = if_else(
      gapfilled,
      (pred_flux_total_se * flux_to_mgC_30min / 1000)^2,
      0
    )
  ) %>%
  reframe(
    .by = c(SITE_ID, Year),
    n_30min = dplyr::n(),
    n_observed = sum(observed_flux, na.rm = TRUE),
    n_gapfilled = sum(gapfilled, na.rm = TRUE),
    observed_coverage = n_observed / n_30min,
    annual_budget_gC_m2_yr = sum(gapfilled_CH4_mgC_30min, na.rm = TRUE) / 1000,
    observed_partial_sum_gC_m2 = sum(observed_CH4_mgC_30min, na.rm = TRUE) / 1000,
    gapfilled_partial_sum_gC_m2 = sum(if_else(gapfilled, gapfilled_CH4_mgC_30min, 0), na.rm = TRUE) / 1000,
    model_prediction_se_gC = sqrt(sum(prediction_variance_gC2, na.rm = TRUE)),
    n_training_obs = max(n_training_obs, na.rm = TRUE)
  ) %>%
  left_join(daily_residual_sd_site, by = "SITE_ID") %>%
  mutate(
    daily_residual_sd_gC = if_else(
      is.finite(daily_residual_sd_gC) & n_residual_days >= 5,
      daily_residual_sd_gC,
      global_daily_residual_sd
    ),
    n_residual_days = replace_na(n_residual_days, 0L),
    gapfilled_days_equiv = n_gapfilled / 48,
    residual_block_se_gC = daily_residual_sd_gC * sqrt(gapfilled_days_equiv),
    annual_budget_sd_gC_m2_yr = sqrt(model_prediction_se_gC^2 + residual_block_se_gC^2),
    annual_budget_lower95_gC_m2_yr = annual_budget_gC_m2_yr - 1.96 * annual_budget_sd_gC_m2_yr,
    annual_budget_upper95_gC_m2_yr = annual_budget_gC_m2_yr + 1.96 * annual_budget_sd_gC_m2_yr,
    quality_flag = case_when(
      n_training_obs < min_training_obs_per_site ~ "population extrapolation",
      observed_coverage < 0.01 ~ "very low observed coverage",
      observed_coverage < 0.05 ~ "low observed coverage",
      TRUE ~ "moderate observed coverage"
    )
  ) %>%
  arrange(SITE_ID, Year)

observed_daily_budget <- gapfilled_30min %>%
  filter(observed_flux, is.finite(observed_CH4_mgC_30min)) %>%
  reframe(
    .by = c(SITE_ID, Year, Date),
    n_observed_30min = dplyr::n(),
    observed_total_partial_gC_m2_day = sum(observed_CH4_mgC_30min, na.rm = TRUE) / 1000,
    observed_total_scaled_gC_m2_day = observed_total_partial_gC_m2_day * 48 / n_observed_30min,
    observed_FG_scaled_gC_m2_day = sum(FG_ENSEMBLE_RSHP_mgC_30min, na.rm = TRUE) * 48 / n_observed_30min / 1000,
    observed_storage_scaled_gC_m2_day = sum(storage_flux_filled_mgC_30min, na.rm = TRUE) * 48 / n_observed_30min / 1000
  ) %>%
  filter(n_observed_30min >= 6)

observed_scaled_annual_budget <- observed_daily_budget %>%
  mutate(days_in_year = if_else(
    (Year %% 4 == 0 & Year %% 100 != 0) | Year %% 400 == 0,
    366,
    365
  )) %>%
  reframe(
    .by = c(SITE_ID, Year),
    n_observed_days = dplyr::n(),
    mean_observed_total_gC_m2_day = mean(observed_total_scaled_gC_m2_day, na.rm = TRUE),
    sd_observed_total_gC_m2_day = sd(observed_total_scaled_gC_m2_day, na.rm = TRUE),
    observed_scaled_annual_gC_m2_yr = mean_observed_total_gC_m2_day * first(days_in_year),
    observed_scaled_annual_se_gC_m2_yr = sd_observed_total_gC_m2_day / sqrt(n_observed_days) * first(days_in_year),
    observed_scaled_annual_lower95_gC_m2_yr = observed_scaled_annual_gC_m2_yr - 1.96 * observed_scaled_annual_se_gC_m2_yr,
    observed_scaled_annual_upper95_gC_m2_yr = observed_scaled_annual_gC_m2_yr + 1.96 * observed_scaled_annual_se_gC_m2_yr,
    observed_FG_scaled_annual_gC_m2_yr = mean(observed_FG_scaled_gC_m2_day, na.rm = TRUE) * first(days_in_year),
    observed_storage_scaled_annual_gC_m2_yr = mean(observed_storage_scaled_gC_m2_day, na.rm = TRUE) * first(days_in_year)
  )

annual_budget <- annual_budget %>%
  left_join(observed_scaled_annual_budget, by = c("SITE_ID", "Year")) %>%
  mutate(
    interpretable_budget = observed_coverage >= min_interpretable_coverage &
      n_training_obs >= min_training_obs_per_site,
    annual_budget_interpretable_gC_m2_yr = if_else(
      interpretable_budget,
      annual_budget_gC_m2_yr,
      NA_real_
    ),
    annual_budget_interpretable_lower95_gC_m2_yr = if_else(
      interpretable_budget,
      annual_budget_lower95_gC_m2_yr,
      NA_real_
    ),
    annual_budget_interpretable_upper95_gC_m2_yr = if_else(
      interpretable_budget,
      annual_budget_upper95_gC_m2_yr,
      NA_real_
    )
  )

mean_annual_budget <- annual_budget %>%
  reframe(
    .by = SITE_ID,
    n_years = dplyr::n(),
    n_interpretable_years = sum(interpretable_budget, na.rm = TRUE),
    mean_observed_coverage = mean(observed_coverage, na.rm = TRUE),
    min_observed_coverage = min(observed_coverage, na.rm = TRUE),
    n_training_obs = max(n_training_obs, na.rm = TRUE),
    mean_annual_budget_gC_m2_yr = mean(annual_budget_gC_m2_yr, na.rm = TRUE),
    median_annual_budget_gC_m2_yr = median(annual_budget_gC_m2_yr, na.rm = TRUE),
    among_year_sd_gC_m2_yr = sd(annual_budget_gC_m2_yr, na.rm = TRUE),
    mean_gapfill_sd_gC_m2_yr = sqrt(sum(annual_budget_sd_gC_m2_yr^2, na.rm = TRUE)) / n_years,
    mean_annual_budget_sd_gC_m2_yr = sqrt(
      replace_na(among_year_sd_gC_m2_yr, 0)^2 / n_years +
        sum(annual_budget_sd_gC_m2_yr^2, na.rm = TRUE) / n_years^2
    ),
    mean_annual_budget_lower95_gC_m2_yr = mean_annual_budget_gC_m2_yr - 1.96 * mean_annual_budget_sd_gC_m2_yr,
    mean_annual_budget_upper95_gC_m2_yr = mean_annual_budget_gC_m2_yr + 1.96 * mean_annual_budget_sd_gC_m2_yr,
    mean_annual_budget_interpretable_gC_m2_yr = if_else(
      n_interpretable_years > 0,
      mean(annual_budget_interpretable_gC_m2_yr, na.rm = TRUE),
      NA_real_
    ),
    mean_annual_budget_interpretable_sd_gC_m2_yr = if_else(
      n_interpretable_years > 0,
      sqrt(
        replace_na(sd(annual_budget_interpretable_gC_m2_yr, na.rm = TRUE), 0)^2 / n_interpretable_years +
          sum(annual_budget_sd_gC_m2_yr[interpretable_budget]^2, na.rm = TRUE) / n_interpretable_years^2
      ),
      NA_real_
    ),
    mean_annual_budget_interpretable_lower95_gC_m2_yr = mean_annual_budget_interpretable_gC_m2_yr -
      1.96 * mean_annual_budget_interpretable_sd_gC_m2_yr,
    mean_annual_budget_interpretable_upper95_gC_m2_yr = mean_annual_budget_interpretable_gC_m2_yr +
      1.96 * mean_annual_budget_interpretable_sd_gC_m2_yr,
    mean_observed_scaled_annual_gC_m2_yr = if_else(
      any(is.finite(observed_scaled_annual_gC_m2_yr)),
      mean(observed_scaled_annual_gC_m2_yr, na.rm = TRUE),
      NA_real_
    ),
    mean_observed_FG_scaled_annual_gC_m2_yr = if_else(
      any(is.finite(observed_FG_scaled_annual_gC_m2_yr)),
      mean(observed_FG_scaled_annual_gC_m2_yr, na.rm = TRUE),
      NA_real_
    ),
    mean_observed_storage_scaled_annual_gC_m2_yr = if_else(
      any(is.finite(observed_storage_scaled_annual_gC_m2_yr)),
      mean(observed_storage_scaled_annual_gC_m2_yr, na.rm = TRUE),
      NA_real_
    ),
    quality_flag = case_when(
      n_training_obs < min_training_obs_per_site ~ "population extrapolation",
      mean_observed_coverage < 0.01 ~ "very low observed coverage",
      mean_observed_coverage < 0.05 ~ "low observed coverage",
      TRUE ~ "moderate observed coverage"
    )
  ) %>%
  arrange(mean_annual_budget_gC_m2_yr)

readr::write_csv(
  gapfilled_30min %>%
    dplyr::select(
      SITE_ID, time.rounded, Year, Date, month, doy, hour_num, season,
      observed_flux, gapfilled, flux_total, pred_flux_total, pred_flux_total_se,
      prediction_uses_site_effect, gapfilled_flux_total, observed_CH4_mgC_30min,
      pred_CH4_mgC_30min, FG_ENSEMBLE_RSHP_mgC_30min, storage_flux_filled_mgC_30min,
      gapfilled_CH4_mgC_30min, count, PAR, Tair_C, log_PAR, Tair_filled,
      log_PAR_filled, n_training_obs
    ),
  "OUTPUT/NEON_total_flux_gapfilled_30min.csv.gz"
)

readr::write_csv(observed_daily_budget, "OUTPUT/NEON_total_flux_observed_daily_scaled_budget.csv")
readr::write_csv(observed_scaled_annual_budget, "OUTPUT/NEON_total_flux_observed_scaled_annual_budget.csv")
readr::write_csv(annual_budget, "OUTPUT/NEON_total_flux_annual_budget.csv")
readr::write_csv(mean_annual_budget, "OUTPUT/NEON_total_flux_mean_annual_budget.csv")

budget_plot <- mean_annual_budget %>%
  mutate(SITE_ID = factor(SITE_ID, levels = SITE_ID)) %>%
  ggplot(aes(x = mean_annual_budget_interpretable_gC_m2_yr, y = SITE_ID, color = quality_flag)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey45") +
  geom_point(data = mean_annual_budget %>% filter(is.na(mean_annual_budget_interpretable_gC_m2_yr)),
             aes(x = mean_annual_budget_gC_m2_yr), color = "grey70", size = 1.8, shape = 1) +
  geom_errorbar(
    data = mean_annual_budget %>% filter(is.finite(mean_annual_budget_interpretable_gC_m2_yr)),
    aes(
      xmin = mean_annual_budget_interpretable_lower95_gC_m2_yr,
      xmax = mean_annual_budget_interpretable_upper95_gC_m2_yr
    ),
    orientation = "y",
    width = 0,
    alpha = 0.7,
    na.rm = TRUE
  ) +
  geom_point(
    data = mean_annual_budget %>% filter(is.finite(mean_annual_budget_interpretable_gC_m2_yr)),
    size = 2
  ) +
  theme_bw(base_size = 10) +
  labs(
    x = expression("Mean annual CH"[4] * " total flux budget (g C m"^-2 * " yr"^-1 * ")"),
    y = NULL,
    color = "Quality flag",
    title = "Interpretable gap-filled NEON total CH4 flux annual budgets",
    subtitle = "Filled grey circles show suppressed estimates with less than 5% mean observed coverage or fewer than 50 observations."
  ) +
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "bottom"
  )

ggsave(
  "FIGURES/NEON_total_flux_mean_annual_budget.png",
  plot = budget_plot,
  width = 8,
  height = 10,
  units = "in",
  dpi = 300
)

component_plot <- observed_scaled_annual_budget %>%
  dplyr::select(
    SITE_ID, Year,
    observed_total_scaled_annual_gC_m2_yr = observed_scaled_annual_gC_m2_yr,
    observed_FG_scaled_annual_gC_m2_yr,
    observed_storage_scaled_annual_gC_m2_yr
  ) %>%
  pivot_longer(
    cols = -c(SITE_ID, Year),
    names_to = "component",
    values_to = "annual_budget_gC_m2_yr"
  ) %>%
  mutate(
    component = recode(
      component,
      observed_total_scaled_annual_gC_m2_yr = "Total observed scaled",
      observed_FG_scaled_annual_gC_m2_yr = "Gradient flux component",
      observed_storage_scaled_annual_gC_m2_yr = "Storage component"
    )
  ) %>%
  ggplot(aes(x = component, y = annual_budget_gC_m2_yr, color = component)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey45") +
  geom_boxplot(outlier.shape = NA, alpha = 0.12, width = 0.55) +
  geom_jitter(width = 0.15, alpha = 0.55, size = 1.4) +
  theme_bw(base_size = 10.5) +
  labs(
    x = NULL,
    y = expression("Observed scaled annual CH"[4] * " budget (g C m"^-2 * " yr"^-1 * ")"),
    color = NULL,
    title = "Observed-only scaled annual budgets by total-flux component"
  ) +
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "none",
    axis.text.x = element_text(angle = 20, hjust = 1)
  )

ggsave(
  "FIGURES/NEON_total_flux_observed_component_diagnostics.png",
  plot = component_plot,
  width = 7,
  height = 5,
  units = "in",
  dpi = 300
)

coverage_plot <- annual_budget %>%
  ggplot(aes(x = Year, y = observed_coverage, group = SITE_ID)) +
  geom_line(alpha = 0.35) +
  geom_point(alpha = 0.65, size = 1) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_bw(base_size = 10) +
  labs(
    x = NULL,
    y = "Observed total-flux coverage",
    title = "Observed total-flux coverage by site-year"
  ) +
  theme(plot.title = element_text(face = "bold"))

ggsave(
  "FIGURES/NEON_total_flux_annual_coverage.png",
  plot = coverage_plot,
  width = 8,
  height = 5,
  units = "in",
  dpi = 300
)

quality_lines <- mean_annual_budget %>%
  count(quality_flag, name = "n_sites") %>%
  mutate(line = paste0("- ", quality_flag, ": ", n_sites, " sites")) %>%
  pull(line)

interpretable_lines <- c(
  paste0(
    "- Interpretable site-year budgets: ",
    sum(annual_budget$interpretable_budget, na.rm = TRUE),
    " of ",
    nrow(annual_budget)
  ),
  paste0(
    "- Sites with at least one interpretable year: ",
    sum(mean_annual_budget$n_interpretable_years > 0, na.rm = TRUE),
    " of ",
    nrow(mean_annual_budget)
  )
)

writeLines(
  c(
    "# NEON Total CH4 Flux Annual Budget",
    "",
    paste0("Input total-flux file: `", total_flux_file, "`."),
    "",
    "## Method",
    "- Gap-fill target: `flux_total = FG_ENSEMBLE_RSHP + storage_flux_filled` from `flow.TotalFlux.R`.",
    "- Gap-fill model: Gaussian GAM with diel cycle, day-of-year cycle, filled air temperature, filled log(PAR), temperature-light interaction, season, and site random effect.",
    "- Annual budgets use complete calendar-year half-hour grids for every site-year present in the total-flux object.",
    "- Fluxes are converted to mg C m-2 30 min-1 with the same conversion used in `flow.30min.analysis.R`, then summed to g C m-2 yr-1.",
    "- Uncertainty combines GAM prediction SE for gap-filled intervals with site-level day-scale residual variability. Explicit measurement and storage-flux uncertainty are unavailable in the total-flux product and are not propagated.",
    "- Site random effects are used for prediction only when a site has at least 50 finite total-flux observations. Other sites use population-level predictions.",
    paste0("- Interpretable budget columns are retained only for site-years with at least ", min_interpretable_coverage * 100, "% observed total-flux coverage and at least 50 finite site observations."),
    "",
    "## Site Quality Flags",
    quality_lines,
    "",
    "## Interpretable Budget Counts",
    interpretable_lines,
    "",
    "## Outputs",
    "- `OUTPUT/NEON_total_flux_gapfilled_30min.csv.gz`",
    "- `OUTPUT/NEON_total_flux_observed_daily_scaled_budget.csv`",
    "- `OUTPUT/NEON_total_flux_observed_scaled_annual_budget.csv`",
    "- `OUTPUT/NEON_total_flux_annual_budget.csv`",
    "- `OUTPUT/NEON_total_flux_mean_annual_budget.csv`",
    "- `OUTPUT/NEON_total_flux_gapfill_model_summary.txt`",
    "- `FIGURES/NEON_total_flux_mean_annual_budget.png`",
    "- `FIGURES/NEON_total_flux_annual_coverage.png`",
    "- `FIGURES/NEON_total_flux_observed_component_diagnostics.png`"
  ),
  "OUTPUT/NEON_total_flux_annual_budget_results.md"
)

message("Wrote NEON total flux gap-filled annual budget outputs.")

